### ISSUE TITLE
Image tracking with custom marker not working properly

### ISSUE THREAD

**Issue by araujokth** [miralabs/mira-unity-sdk#10]
Brief description of issue:

Hi, I was now trying to add a custom marker to the WikiMiraTemplate.Unity scene. I followed the online instructions and in Unity went to Window/WTC Editor and then added my custom marker (png image) where I confirmed that the dimensions of the marker in the png image are the same as the printed marker - in GIMP it says that the print size is 80 mm width which is the same as the printed marker - and added it to "MiraTrackers". Then went to the MiraTracker gameobject and checked that it appeared there and set my custom marker to "active" (all others active as well). 

If I run the example (not using preview), the original Mira marker gets properly detected and the spiral is displayed. If I then put my custom marker, the spiral is displayed but it is displayed not on top of my marker but very close to my eyes (becomes very large) and the movement of the spiral follows the movement of the marker (I rotated it by hand and the spiral rotates in the same way).  Any idea why the spiral display would not be the same for my custom marker as it is for the original Mira marker?

Another thing is that if I click to "preview" for some reason the marker is not displayed in the scene, while the original Mira markers are.

I also noticed now that when opening the "Mira_Beta_Small.png" in GIMP it says that the print size of the image is a square of 361.24 mm width but that is not the size of the printed marker, which is 133.0 mm. Is this correct? Does this mean that there is a difference between the size of the printed marker and the print size of the png image?

Thanks!

___

This issue was found on:
 * Mira Unity SDK version number: 0.7.0
 * Mira headset version: 
 * Unity version number: 2017.2.0F3
 * Phone model and OS version number: iPhone 8
 * XCode Version number: 9.2 (9C40b)

**Comment by cbarronmira** [comment]
Hi @araujokth, the marker not showing up when you hit the preview button in the inspector seems to indicate that the size was not applied in the WTC editor - Can you double check that the marker size has been input and applied?
![image](https://user-images.githubusercontent.com/31075468/38573568-5efd941a-3cab-11e8-887e-1ad9e216ac26.png)

The marker size you should input is not the marker size of the image in GIMP, but the physical, measured length of the printed marker - the digital image size is ignored

**Comment by araujokth** [comment]
oops. Sorry about that and many thanks. Totally missed that there were input parameters for the dimensions there. Will test that tomorrow!

**Comment by araujokth** [comment]
Now it works! thanks a lot!
