### ISSUE TITLE
Mira Live Preview marker tracking not working

### ISSUE THREAD

**Issue by araujokth** [miralabs/mira-unity-sdk#12]
Brief description of issue: I followed the instructions for the Mira Live Preview and was trying to do marker tracking. Unfortunately it does not work to track the marker when running both the WikiMiraTemplate and the Tracking tutorials. I get an error in the console in Unity which says "The current platfrom (OSXEditor) is not supported by the Wikitude Unity Plugin". The head tracking works well as I rotate my head I see both the editor and the phone content changing, however the spiral is never displayed when the marker is visible. The app works if not run in live preview.

All the instructions you had regarding the quality https://developer.mirareality.com/docs/mira-live-preview#section-configuring-quality-settings-to-use-live-preview were already setup and also the metal was already disabled. 
___

This issue was found on:
 * Mira Unity SDK version number: 0.7.0
 * Mira headset version: -
 * Unity version number: 2017.2.0f3
 * Phone model and OS version number: iPhone 8
 * XCode Version number: 

___

Error messages or logs - Output from console in unity
``` 
You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent().  Alternatively, your script can inherit from ScriptableObject or no base class at all
UnityEngine.MonoBehaviour:.ctor()
RemoteManager:.ctor() (at Assets/MiraSDK/Scripts/BTRemote/RemoteManager.cs:79)
RemoteManager:.cctor() (at Assets/MiraSDK/Scripts/BTRemote/RemoteManager.cs:32)

The current platfrom (OSXEditor) is not supported by the Wikitude Unity Plugin
UnityEngine.Debug:Log(Object)
Wikitude.WikitudeSDK:.cctor()
WikitudeEditor.WikitudeEditorExtension:CheckCompatibility()
WikitudeEditor.WikitudeEditorExtension:CheckCompatibility()
WikitudeEditor.WikitudeEditorExtension:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

Destroying background camera when it doesn't exits yet
UnityEngine.Debug:LogError(Object)
Wikitude.WikitudeCamera:InitializeCamera()
Wikitude.WikitudeCamera:Awake()

besides other messages
```

**Comment by cbarronmira** [comment]
Hi, can you post your log from xcode, when building live preview? Specifically when building live preview, was the bundle ID changed to com.mirareality.livepreview, rather than the default (com.mirareality.example)? The bundle id for live preview is different, so that your actual builds don't overwrite LP - but without that specific bundle identifier, tracking won't work

**Comment by araujokth** [comment]
That was the problem. Sorry for missing that note on the instructions page, but since I had seen already the notice saying that for the new SDK you had to switch to "com.mirareality.example" (instead of com.wikitude.miraexample) for the other examples, I read that quickly thinking and thought it was the exact same notice as I had seen before.
