### ISSUE TITLE
Wikitude Image Tracking Doesn't Work with Custom Targets

### ISSUE THREAD

**Issue by maxmaynard** [miralabs/mira-unity-sdk#6]
Brief description of issue:
No custom images can be implemented and then recognized on runtime. Target tracking works with default images as long as the MiraTrackers.wtc file hasn't been added to, but adding new targets and creating new .wtc files (and trying to use them) results in non-responsive runtimes and builds.

This issue was found on:
 * Mira Unity SDK version number: 0.6.0, 0.7.0, 0.7.1
 * Mira headset version:  For the iPhone 6, 6s, and 7
 * Unity version number: 2017.2.0f, 2017.3.0f
 * Phone model and OS version number: iPhone 6 OS 11.2.6
 * XCode Version number: 9.2 (9C40b)
 
How to reproduce the issue:
  1. Load any new image into the WTC Editor.
  2. Modify size as appropriate.
  3. Build or run Live Preview and test target recognition (if you don't get a SIGABRT on a random thread citing an NSRangeException).
  
 
Additional comments:

Error messages or logs
```
XCode will show a SIGABRT on differing threads citing an NSRangeException or the like.
```

**Comment by Putridbeast** [comment]
I have gotten this to work (kinda). I created a new .wtc file with a default image and a custom image with appropriate sizes and set that as my ImageTracker target collection. Unlike @maxmaynard my builds are responsive as long as metal graphics API is not included, though they may crash on start every other time or so. once started, they do not have a crashing problem that I have observed. the default image can still be tracked, but the custom asset can only barely be tracked. the image is in black and white, and while it has very distinct shapes and colors, it is not nearly as visually complex as the default Mira targets. 

I was only able to track it for a few seconds in a few minutes of trying, so i'm going to look into creating a more visually distinct asset to track.

using:
- mira sdk 7.1
- Unity 2017.2.1f1
- Iphone 6 OS 11.2.6

steps are similar:
1. create new .wtc in the WTC editor with the new image you want and one of the default images for safety
2. modify size as appropriate
3. build the app and test the recognition

note: Live preview won't recognize unless you have already done the same process for the live preview app

**Comment by sterlingcrispin** [comment]
@Wilsoner @maxmaynard have either of you been able to modify the scene 103 Tracking Example and had success building that to a device? Or is the problem only with the live preview app?

**Comment by Putridbeast** [comment]
I was able to deploy the normal 103 scene, with no custom markers without issue. this isn't a problem of the live preview app, though it seems like the live preview has its own issues when trying to recognize images. 

for example, live preview did not fire off the events for OnImageRecognized and OnImageLost for me in the editor.

**Comment by sterlingcrispin** [comment]
@Wilsoner I was able to modify the 103 scene with a custom marker by adding an image into MiraTrackers .wtc file in the WTC editor, I've found its important to specify the size in MM otherwise its hard to tell if its actually tracking on the device, can you try to do that and see if it works?

I've also been able to do the same and build the LivePreview app and have it recognize this new image and stream tracking data back to the editor without any problems. 

This was all on 2017.3 on an Iphone 6S os 10.2, I'll try to update the iOS version and see if thats whats breaking it

**Comment by sterlingcrispin** [comment]
@maxmaynard can you post the full error logs you're receiving ?

**Comment by maxmaynard** [comment]
Sure, but the crashes are infrequent; I fear I misrepresented the problem. The primary issue is in image tracking; I have not received any response with a custom image, even when adding a new image to Tutorial 103, either in its own file or in the MiraTrackers.wtc. 

How precise does the mm measurement need to be? I have a close approximation of +- 3-5 mm I expect, but I haven't done a hard measurement in a while, so perhaps I miscalculated.

**Comment by sterlingcrispin** [comment]
@maxmaynard I used a pair of calipers to measure my target but I'd think +- a few millimeters wouldn't create the kinds of issues you're seeing, it would likely just change the scale and orientation of the AR content

Have you tried starting from an empty fresh unity project? 
What is your bundle ID for the app?  Are you on a paid iOS developer account?

Have you made sure to set the recommended app settings in file menu Mira > Settings ? I'm curious if the auto rotation was set, and if its also set in the Xcode area for it, because that can cause unwanted behavior in apps unrelated to image tracking.

**Comment by maxmaynard** [comment]
That's more or less what I figured. I should be getting some kind of response but I'm not.

I did try it with a fresh project, and every available Mira SDK as well as the two latest versions of Unity. The bundle ID shouldn't matter and I am on a paid iOS account. I've used the recommended settings as well as other tweaks. Even if there was unwanted behavior with the target there would still be some reaction, even with some kind of auto rotation, right?

**Comment by Putridbeast** [comment]
@maxmaynard  i'm fairly certain the bundle id does matter. it looks like there is a specific key tied to each bundle id, and if you wanted to use another you would have to register it with wikitude i guess. 

see https://developer.mirareality.com/docs/wikitude-development-api-keys

**Comment by sterlingcrispin** [comment]
Yep thats right, it's also documented at https://developer.mirareality.com/docs/gotchas and elsewhere 

Max can you try building with this bundle ID and see if your issue gets resolved?

**Comment by maxmaynard** [comment]
So that fixed the issue I was having where no targets were working. The default MiraTrackers started working again even when I had a custom tracker added to that .wtc, but I wasn't able to get my custom marker to track.

**Comment by cbarronmira** [comment]
When you hit the preview button in the inspector (on the Tracker gameobject), does your custom tracker show up in the scene? That's helpful to test if the scale settings were applied in the wtc editor. You should also try tracking with the lens off, to make sure it's not due to glare or lighting

**Comment by maxmaynard** [comment]
Seems it works fine; just the printout interfering. Testing the image tracking using a computer monitor resulted in tracking working as intended.
