### ISSUE TITLE
Accessing the camera stream

### ISSUE THREAD

**Issue by araujokth** [miralabs/mira-unity-sdk#8]
Hi,

I was wondering if there was any simple way to access the camera stream when running one of your applications?

Thanks for the help!

**Comment by cbarronmira** [comment]
Hi @araujokth, the camera feed can be accessed through the "WikitudeCamera.CameraTexture" parameter; The WikitudeCamera component is on the MiraArCamera GameObject

**Comment by araujokth** [comment]
Thanks! Will check that out
